import { GAME_CONFIG, PERSONALITY_TRAITS, QUEST_STATES } from '../constants/gameConfig.js';

// Initial game state structure
export const createInitialGameState = (userId, worldName) => ({
  // Meta information
  userId,
  gameId: `game_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
  worldName,
  createdAt: Date.now(),
  lastSavedAt: Date.now(),
  
  // Progress tracking
  currentTurn: 1,
  currentStage: 1,
  totalTurns: GAME_CONFIG.TOTAL_TURNS,
  
  // Player personality profile (hidden until revealed)
  profile: {
    aggression: 0.5,
    caution: 0.5,
    morality: 0.5,
    creativity: 0.5,
    leadership: 0.5,
    loyalty: 0.5,
    independence: 0.5,
    diplomacy: 0.5,
    revealed: false, // Shows at turn 25 (halfway)
    profileHistory: [], // Track changes over time
  },
  
  // World context (generated by World Builder Agent)
  world: {
    name: worldName,
    description: "",
    atmosphere: "",
    lore: "",
    currentLocation: "",
    availableLocations: [],
    worldState: {}, // Dynamic world properties
  },
  
  // NPCs (max 15 active)
  npcs: [],
  npcRelationships: {}, // { npcId: relationshipValue }
  
  // Player group/party
  group: {
    members: [], // NPCs who joined the player
    maxSize: GAME_CONFIG.MAX_GROUP_SIZE,
    morale: 100,
    cohesion: 50,
  },
  
  // Quests
  quests: {
    main: null, // Main quest (always active)
    side: [], // Side quests (max 3 active per stage)
    completed: [],
    failed: [],
  },
  
  // Inventory
  inventory: {
    items: [],
    maxSize: GAME_CONFIG.MAX_INVENTORY_SIZE,
    gold: 0,
  },
  
  // Player stats
  stats: {
    health: 100,
    maxHealth: 100,
    reputation: 0, // -100 to 100
    survivalDays: 0,
    kills: 0,
    alliesSaved: 0,
    betrayalsCommitted: 0,
    betrayalsSuffered: 0,
  },
  
  // Turn history (stores all decisions)
  history: [],
  
  // Current scene context
  currentScene: {
    description: "",
    atmosphere: "",
    npcsPresent: [],
    availableActions: [],
    threat: 0, // 0-100
  },
  
  // Flags for story events
  storyFlags: {},
  
  // Cache for performance
  cache: {
    lastNarrativeGenerated: null,
    commonDialogues: {},
    frequentChoices: {},
  },
  
  // Game outcome (filled at end)
  outcome: null,
});

// NPC structure
export const createNPC = (data) => ({
  id: data.id || `npc_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
  name: data.name,
  archetype: data.archetype,
  description: data.description || "",
  
  // Personality traits
  traits: {
    aggression: data.traits?.aggression || 0.5,
    caution: data.traits?.caution || 0.5,
    morality: data.traits?.morality || 0.5,
    loyalty: data.traits?.loyalty || 0.5,
    greed: data.traits?.greed || 0.5,
    courage: data.traits?.courage || 0.5,
  },
  
  // Relationship with player
  relationship: data.relationship || 0, // -100 to 100
  
  // Status
  alive: true,
  inGroup: false,
  location: data.location || "",
  
  // Memory of interactions
  memory: [],
  firstMet: data.firstMet || null,
  lastSeen: data.lastSeen || null,
  
  // Secrets and knowledge
  secrets: data.secrets || [],
  knowledge: data.knowledge || [],
  
  // Combat stats (if relevant)
  combatStats: {
    health: data.combatStats?.health || 100,
    attack: data.combatStats?.attack || 10,
    defense: data.combatStats?.defense || 10,
  },
  
  // Inventory (what they can give/trade)
  inventory: data.inventory || [],
  
  // Betrayal potential
  betrayalRisk: 0, // 0-100, calculated by Betrayal Agent
  canBetray: data.canBetray !== false,
  betrayalTriggers: data.betrayalTriggers || [],
});

// Quest structure
export const createQuest = (data) => ({
  id: data.id || `quest_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
  name: data.name,
  type: data.type, // 'main' or 'side'
  stage: data.stage,
  description: data.description,
  
  // Objectives
  objectives: data.objectives || [],
  currentObjective: 0,
  
  // Status
  state: QUEST_STATES.AVAILABLE,
  progress: 0, // 0-100
  
  // Requirements
  requiredItems: data.requiredItems || [],
  requiredNPCs: data.requiredNPCs || [],
  requiredStats: data.requiredStats || {},
  
  // Rewards
  rewards: {
    gold: data.rewards?.gold || 0,
    items: data.rewards?.items || [],
    reputation: data.rewards?.reputation || 0,
    experience: data.rewards?.experience || 0,
  },
  
  // Time limit (in turns, optional)
  turnsRemaining: data.turnsRemaining || null,
  expiresAt: data.expiresAt || null,
  
  // Consequences of failure/success
  successConsequence: data.successConsequence || "",
  failureConsequence: data.failureConsequence || "",
  
  // Related NPCs
  questGiver: data.questGiver || null,
  involvedNPCs: data.involvedNPCs || [],
});

// Item structure
export const createItem = (data) => ({
  id: data.id || `item_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
  name: data.name,
  type: data.type, // weapon, armor, consumable, quest, key, crafting
  description: data.description || "",
  
  // Properties
  stackable: data.stackable || false,
  quantity: data.quantity || 1,
  maxStack: data.maxStack || 1,
  
  // Stats (for weapons/armor)
  stats: data.stats || {},
  
  // Durability (for weapons/armor)
  durability: data.durability || null,
  maxDurability: data.maxDurability || null,
  
  // Quest relevance
  questItem: data.questItem || false,
  relatedQuests: data.relatedQuests || [],
  
  // Value
  value: data.value || 0,
  
  // Special properties
  consumable: data.consumable || false,
  uses: data.uses || null,
  effect: data.effect || null,
  
  // Crafting
  craftable: data.craftable || false,
  recipe: data.recipe || null,
  
  // Lore
  lore: data.lore || "",
  acquiredAt: data.acquiredAt || null,
});

// History entry structure
export const createHistoryEntry = (data) => ({
  turn: data.turn,
  stage: data.stage,
  
  // Scene context
  scene: data.scene || "",
  location: data.location || "",
  npcsPresent: data.npcsPresent || [],
  
  // Player action
  choiceIndex: data.choiceIndex, // 0-3
  choiceText: data.choiceText,
  choiceType: data.choiceType, // AGGRESSIVE, CAUTIOUS, etc.
  
  // Profile updates
  profileBefore: data.profileBefore || {},
  profileAfter: data.profileAfter || {},
  profileChanges: data.profileChanges || {},
  
  // Consequence
  consequence: data.consequence || "",
  success: data.success,
  
  // Effects
  npcRelationshipChanges: data.npcRelationshipChanges || {},
  questUpdates: data.questUpdates || [],
  itemsGained: data.itemsGained || [],
  itemsLost: data.itemsLost || [],
  statsChanged: data.statsChanged || {},
  
  // Story flags set
  flagsSet: data.flagsSet || [],
  
  timestamp: Date.now(),
});

// Memory entry for NPCs
export const createMemoryEntry = (data) => ({
  turn: data.turn,
  action: data.action,
  playerChoice: data.playerChoice || "",
  sentiment: data.sentiment, // -1 to 1
  importance: data.importance, // 0-1
  category: data.category, // help, harm, betray, gift, etc.
  description: data.description || "",
  witnesses: data.witnesses || [], // Other NPCs who saw this
});

// Game state helper functions
export const GameStateHelpers = {
  // Get current stage info
  getCurrentStage: (gameState) => {
    const { STAGES } = require('../constants/gameConfig.js');
    return STAGES.find(s => s.id === gameState.currentStage);
  },
  
  // Check if NPC is alive
  isNPCAlive: (gameState, npcId) => {
    const npc = gameState.npcs.find(n => n.id === npcId);
    return npc && npc.alive;
  },
  
  // Get NPC relationship level
  getNPCRelationship: (gameState, npcId) => {
    return gameState.npcRelationships[npcId] || 0;
  },
  
  // Get active quests
  getActiveQuests: (gameState) => {
    return [
      ...(gameState.quests.main ? [gameState.quests.main] : []),
      ...gameState.quests.side.filter(q => q.state === QUEST_STATES.ACTIVE),
    ];
  },
  
  // Check if player has item
  hasItem: (gameState, itemId) => {
    return gameState.inventory.items.some(item => item.id === itemId);
  },
  
  // Get personality profile summary
  getProfileSummary: (gameState) => {
    const profile = gameState.profile;
    const traits = Object.keys(PERSONALITY_TRAITS);
    
    return traits.map(trait => ({
      name: trait,
      value: profile[trait.toLowerCase()],
      label: PERSONALITY_TRAITS[trait].name,
      icon: PERSONALITY_TRAITS[trait].icon,
    })).sort((a, b) => b.value - a.value);
  },
  
  // Calculate dominant personality trait
  getDominantTrait: (gameState) => {
    const summary = GameStateHelpers.getProfileSummary(gameState);
    return summary[0];
  },
  
  // Check if in group mode or solo
  isGroupMode: (gameState) => {
    return gameState.group.members.length > 0;
  },
  
  // Get available inventory space
  getAvailableInventorySpace: (gameState) => {
    return gameState.inventory.maxSize - gameState.inventory.items.length;
  },
};

export default {
  createInitialGameState,
  createNPC,
  createQuest,
  createItem,
  createHistoryEntry,
  createMemoryEntry,
  GameStateHelpers,
};